require "has_unique_three_letter_code/configuration"
require "has_unique_three_letter_code/class_methods"
require "has_unique_three_letter_code/instance_methods"
require "has_unique_three_letter_code/version"

module HasUniqueThreeLetterCode
end
